FI.WebAtividadeEntrevista/Controllers/BeneficiarioController.cs
using FI.AtividadeEntrevista.BLL;
using FI.AtividadeEntrevista.DML;
using FI.Utils.Exceptions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebAtividadeEntrevista.Models;

namespace WebAtividadeEntrevista.Controllers
{
    public class BeneficiarioController : Controller
    {
        private readonly BoBeneficiario _boBeneficiario;

        public BeneficiarioController(BoBeneficiario boBeneficiario)
        {
            _boBeneficiario = boBeneficiario;
        }

        [HttpPost]
        public JsonResult Incluir(FormModel model)
        {

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {

                try
                {
                    model.ModalId = _boBeneficiario.Incluir(GetBeneficiarioByModel(model));
                    return Json("Cadastro efetuado com sucesso");
                }
                catch (CpfJaExisteException ex)
                {
                    Response.StatusCode = 400;
                    return Json(ex.Message);
                }
            }
        }

        private static Beneficiario GetBeneficiarioByModel(FormModel model)
        {
            return new Beneficiario()
            {
                Nome = model.ModalNome,
                CPF = model.ModalCPF
            };
        }

        [HttpPost]
        public JsonResult Alterar(FormModel model)
        {
            var bo = new BoBeneficiario();

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                var beneficiario = GetBeneficiarioByModel(model);
                beneficiario.Id = model.ModalId;
                _boBeneficiario.Alterar(beneficiario);

                return Json("Cadastro alterado com sucesso");
            }
        }

        [HttpGet]
        public ActionResult Alterar(long id)
        {
            var bo = new BoBeneficiario();
            Beneficiario beneficiario = bo.Consultar(id);
            BeneficiarioModel model = null;

            if (beneficiario != null)
            {
                model = new BeneficiarioModel()
                {
                    ModalNome = beneficiario.Nome,
                    ModalCPF = beneficiario.Nome
                };


            }

            return View(model);
        }

        [HttpPost]
        public JsonResult BeneficiarioList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                var qtd = 0;
                string campo = string.Empty;
                string crescente = string.Empty;
                string[] array = jtSorting.Split(' ');

                if (array.Length > 0)
                    campo = array[0];

                if (array.Length > 1)
                    crescente = array[1];

                List<Beneficiario> beneficiarios = _boBeneficiario.Pesquisa(jtStartIndex, jtPageSize, campo, crescente.Equals("ASC", StringComparison.InvariantCultureIgnoreCase), out qtd);

                //Return result to jTable
                return Json(new { Result = "OK", Records = beneficiarios, TotalRecordCount = qtd });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

FI.WebAtividadeEntrevista/Controllers/ClienteController.cs
using FI.AtividadeEntrevista.BLL;
using WebAtividadeEntrevista.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using FI.AtividadeEntrevista.DML;
using FI.Utils.Exceptions;

namespace WebAtividadeEntrevista.Controllers
{
    public class ClienteController : Controller
    {
        private readonly BoCliente _boCliente;

        public ClienteController(BoCliente boCliente)
        {
            _boCliente = boCliente;
        }

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Incluir(FormModel model)
        {
            
            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {

                try
                {
                    model.Id = _boCliente.Incluir(GetClienteByModel(model));
                    return Json("Cadastro efetuado com sucesso");
                }
                catch (CpfJaExisteException ex)
                {
                    Response.StatusCode = 400;
                    return Json(ex.Message);
                }
            }
        }

        private static Cliente GetClienteByModel(FormModel model)
        {
            return new Cliente()
            {
                CEP = model.CEP,
                Cidade = model.Cidade,
                Email = model.Email,
                Estado = model.Estado,
                Logradouro = model.Logradouro,
                Nacionalidade = model.Nacionalidade,
                Nome = model.Nome,
                Sobrenome = model.Sobrenome,
                Telefone = model.Telefone,
                CPF = model.CPF
            };
        }

        [HttpPost]
        public JsonResult Alterar(FormModel model)
        {
            BoCliente bo = new BoCliente();
       
            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                var cliente = GetClienteByModel(model);
                cliente.Id = model.Id;
                _boCliente.Alterar(cliente);
                               
                return Json("Cadastro alterado com sucesso");
            }
        }

        [HttpGet]
        public ActionResult Alterar(long id)
        {
            BoCliente bo = new BoCliente();
            Cliente cliente = bo.Consultar(id);
            Models.FormModel model = null;

            if (cliente != null)
            {
                model = new FormModel()
                {
                    Id = cliente.Id,
                    CEP = cliente.CEP,
                    Cidade = cliente.Cidade,
                    Email = cliente.Email,
                    Estado = cliente.Estado,
                    Logradouro = cliente.Logradouro,
                    Nacionalidade = cliente.Nacionalidade,
                    Nome = cliente.Nome,
                    Sobrenome = cliente.Sobrenome,
                    Telefone = cliente.Telefone,
                    CPF = cliente.CPF
                };

            
            }

            return View(model);
        }

        [HttpPost]
        public JsonResult ClienteList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                var qtd = 0;
                string campo = string.Empty;
                string crescente = string.Empty;
                string[] array = jtSorting.Split(' ');

                if (array.Length > 0)
                    campo = array[0];

                if (array.Length > 1)
                    crescente = array[1];

                List<Cliente> clientes = _boCliente.Pesquisa(jtStartIndex, jtPageSize, campo, crescente.Equals("ASC", StringComparison.InvariantCultureIgnoreCase), out qtd);

                //Return result to jTable
                return Json(new { Result = "OK", Records = clientes, TotalRecordCount = qtd });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

FI.WebAtividadeEntrevista/Views/Cliente/Alterar.cshtml
@model WebAtividadeEntrevista.Models.FormModel
@{
    ViewBag.Title = "Alterar Cliente";
}
@section scripts{
<script>
        var urlPost = '@Url.Action("Alterar", "Cliente", new { area = "" })';
        var obj = @Html.Raw(Json.Encode(Model));
        var urlRetorno = '@Url.Action("Index", "Cliente", new { area = "" })';
</script>
    @Scripts.Render("~/bundles/altClientes")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")

FI.WebAtividadeEntrevista/Views/Cliente/Forms.cshtml
@model WebAtividadeEntrevista.Models.FormModel
@using WebAtividadeEntrevista.Models

@using (Html.BeginForm("Incluir", "Cliente", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Nome, new { htmlAttributes = new { @class = "" } })
                @Html.EditorFor(m => m.Nome, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Sobrenome, new { htmlAttributes = new { @class = "" } })
                @Html.EditorFor(m => m.Sobrenome, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.CPF, new { htmlAttributes = new { @class = "" } })
                @Html.EditorFor(m => m.CPF, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Nacionalidade, new { htmlAttributes = new { @class = "" } })
                @Html.EditorFor(m => m.Nacionalidade, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(m => m.CEP, new { htmlAttributes = new { @class = "" } })
                @Html.EditorFor(m => m.CEP, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Estado, new { htmlAttributes = new { @class = "" } })

                @Html.DropDownList("Estado",
                    new SelectList(Enum.GetNames(typeof(StateEnum))),
                    "Estado",
                     new { @class = "form-control" })
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Cidade, new { htmlAttributes = new { @class = "" } })
                @Html.EditorFor(m => m.Cidade, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                @Html.LabelFor(m => m.Cidade, new { htmlAttributes = new { @class = "" } })
                @Html.EditorFor(m => m.Cidade, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Email, new { htmlAttributes = new { @class = "" } })
                @Html.EditorFor(m => m.Email, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Telefone, new { htmlAttributes = new { @class = "" } })
                @Html.EditorFor(m => m.Telefone, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    </div>
    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">Beneficiários</button>
    <div class="row">
        <div class="col-lg-12">
            <div class="pull-right">
                <button type="submit" id="btnIncluirCliente" class="btn btn-sm btn-success">Salvar</button>
                @Html.ActionLink("Voltar", "Index", "Cliente", new { }, new { @class = "btn btn-sm btn-danger" })
            </div>
        </div>
    </div>


}

@section scripts{
    <script>
    var urlAlteracao = '@Url.Action("Alterar", "Beneficiario", new { area = "" })';
    var urlClienteList = '@Url.Action("BeneficiarioList", "Beneficiario", new { area = "" })';

    </script>
    @Scripts.Render("~/bundles/listBeneficiarios")
}

<!-- Modal -->
<div class="modal fade" id="myModal">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Beneficiários</h4>
            </div>
            <div class="modal-body">
                <form id="formCadastro" method="post">

                    <div class="row align-items-center">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="ModalNome">Nome:</label>
                                <input required="required" type="text" class="form-control" id="ModalNome" name="ModalNome" placeholder="Ex.: João" maxlength="50">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="ModalCPF">CPF:</label>
                                <input required="required" type="text" class="form-control" id="ModalCPF" name="ModalCPF" placeholder="Ex.: 010.011.111-00" maxlength="14">
                            </div>
                        </div>
                        <div class="col-md-4 button-center" style="height:13vh;">
                            <button type="submit" class="btn btn-success" id="btnIncluirBenef">Incluir</button>
                        </div>
                    </div>
                </form>
                <table id="gridBeneficiarios" class="table"></table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

FI.WebAtividadeEntrevista/Views/Cliente/Incluir.cshtml
@{
    ViewBag.Title = "Cadastrar Cliente";
}
@section scripts{
    <script>
        var urlPost = '@Url.Action("Incluir", "Cliente", new { area = "" })';
        var obj = @Html.Raw(Json.Encode(Model));

    </script>
    @Scripts.Render("~/bundles/clientes")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")

FI.WebAtividadeEntrevista/Views/Cliente/Index.cshtml
@{
    ViewBag.Title = "Clientes";
}
@section scripts{
<script>
    var urlAlteracao = '@Url.Action("Alterar", "Cliente", new { area = "" })';
    var urlClienteList = '@Url.Action("ClienteList", "Cliente", new { area = "" })';

</script>
    @Scripts.Render("~/bundles/listClientes")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.ActionLink("Novo Cliente", "Incluir", "Cliente", new { }, new { @class= "btn btn-sm btn-primary pull-right" })
<table id="gridClientes" class="table"></table>

FI.WebAtividadeEntrevista/Views/Cliente/Modal.cshtml
@model WebAtividadeEntrevista.Models.BeneficiarioModel
<!-- Modal -->
<div class="modal fade" id="myModal">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Beneficiários</h4>
            </div>
            <div class="modal-body">
                <form id="formBeneficiario" action="~/Beneficiario/Incluir" role="form" method="post">
                    <div class="row align-items-center">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="ModalNome">Nome:</label>
                                <input required="required" type="text" class="form-control" id="ModalNome" name="ModalNome" placeholder="Ex.: João" maxlength="50">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="ModalCPF">CPF:</label>
                                <input required="required" type="text" class="form-control" id="ModalCPF" name="ModalCPF" placeholder="Ex.: 010.011.111-00" maxlength="14">
                            </div>
                        </div>
                        <div class="col-md-4 button-center" style="height:13vh;">
                            <button type="button" class="btn btn-success" onclick="document.forms[1].submit()">Incluir</button>
                        </div>
                    </div>
                </form>
                <table id="gridBeneficiarios" class="table"></table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>